#!/bin/bash

set -e

cd ~
[ ! -d dotfiles ] && echo "ERROR: dotfiles dir must be in ~." && exit 1
rm -rf dotfiles_bak
mkdir dotfiles_bak

deploy_core(){
  target="$1"
  link_name="$2"
  [ "$link_name" = "" ] && link_name="$target"
  target="$(readlink -m dotfiles/$target)"  # absolute path
  if [ -e "$link_name" ] || [ -h "$link_name" ]
  then
    mv "$link_name" dotfiles_bak
  fi
  mkdir -p "$(dirname $link_name)"
  ln -sv $target $link_name
}

deploy_core .bash_profile
deploy_core .bashrc
deploy_core bin
deploy_core .config/alacritty
deploy_core .config/compton.conf
deploy_core .config/compton.conf .config/picom.conf
deploy_core .config/dunst
deploy_core .config/emoji
deploy_core .config/flake8
deploy_core .config/fontconfig
deploy_core .config/htop
deploy_core .config/i3
deploy_core .config/nvim
deploy_core .config/rofi
deploy_core .emacs
deploy_core .gitconfig
deploy_core .screenrc
deploy_core .tigrc
deploy_core .tmux.conf
deploy_core .toprc
deploy_core .vim
deploy_core .vimrc
deploy_core .vnc/passwd
deploy_core .Xresources
