#!/bin/bash

# before running this script:
#   /usr/sbin/usermod -aG sudo <username>
#   sudo apt install git
#   git clone http://github.com/antoinemadec/dotfiles
#   ./deploy

set -e
sudo -nv || { echo "Use sudo in this terminal before running the script"; exit 1; }

print_banner() {
  cat << EOF

#--------------------------------------------------------------
# $1
#--------------------------------------------------------------
EOF
}

#--------------------------------------------------------------
# not compiled from source
#--------------------------------------------------------------
print_banner "misc"
sudo apt -y install git tig htop neovim
sudo apt -y install grub-customizer
sudo apt -y install libreoffice evince gnome-calculator
sudo apt -y install software-properties-common
sudo apt -y install arandr pavucontrol rofi scrot x11vnc feh jq compton numlockx gsimplecal
sudo apt -y install pulseaudio-module-bluetooth
sudo apt -y install py3status acpi xclip imagemagick xbacklight

print_banner "fonts"
sudo apt -y install fonts-inconsolata
sudo apt -y install ttf-ancient-fonts
sudo apt -y install fonts-noto-color-emoji libfreetype6 fontconfig libcairo-gobject2 libcairo2
#--------------------------------------------------------------

#--------------------------------------------------------------
# compiled from source
#--------------------------------------------------------------
# dependencies:
#-- termite
sudo apt -y install vte-2.91
#-- pinta
sudo apt -y install mono-xbuild automake autoconf gtk-sharp2 yelp-tools intltool
sudo apt -y install liblua5.1-dev luajit libluajit-5.1 python-dev ruby-dev libperl-dev libncurses5-dev libatk1.0-dev libx11-dev libxpm-dev libxt-dev gnome-devel
#-- i3-gaps
sudo apt -y install gcc make dh-autoreconf libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev xcb libxcb1-dev libxcb-icccm4-dev libyajl-dev libev-dev libxcb-xkb-dev libxcb-cursor-dev libxkbcommon-dev libxcb-xinerama0-dev libxkbcommon-x11-dev libstartup-notification0-dev libxcb-randr0-dev libxcb-xrm0 libxcb-xrm-dev libxcb-shape0-dev
sudo apt -y install i3lock
#-- vim
sudo apt -y install libgtk-3-dev liblua5.1-dev luajit libluajit-5.1 python3-dev python-dev ruby-dev libperl-dev libncurses5-dev libatk1.0-dev libx11-dev libxpm-dev libxt-dev gnome-devel

mkdir -p ~/src

print_banner "termite"
cd ~/src
pwd
git clone https://github.com/Corwind/termite-install
cd termite-install
./termite-install.sh

print_banner "pinta"
cd ~/src
git clone https://github.com/PintaProject/Pinta
cd Pinta
./autogen.sh
make
sudo make install

print_banner "i3-gaps"
i3_upgrade
cd ~/.config/i3/bin/i3lock
git submodule update --init --recursive
git pull --recurse-submodule
cat << EOF | sudo tee /etc/X11/xorg.conf
Section "Device"
        Identifier  "Intel Graphics"
        Driver      "intel"
        Option      "Backlight"  "intel_backlight"
EndSection
EOF

print_banner "vim"
vim_upgrade
#--------------------------------------------------------------

print_banner "gtk theme"
sudo apt -y install lxappearance gtk-chtheme qt4-qtconfig
cat << EOF
lxappearance  : choose a theme
gtk-chtheme   : choose same theme
qtconfig      : dropdown menu setting to make qt take the GTK+ settings
EOF
