#!/bin/bash

# before running this script:
#   /usr/sbin/usermod -aG sudo <username>
#   sudo apt install git
#   git clone http://github.com/antoinemadec/dotfiles
#   ./deploy

set -e
sudo -nv || { echo "Use sudo in this terminal before running the script"; exit 1; }

print_banner() {
  cat << EOF

#--------------------------------------------------------------
# $1
#--------------------------------------------------------------
EOF
}

#--------------------------------------------------------------
# not compiled from source
#--------------------------------------------------------------
print_banner "misc"
sudo apt -y install git tig htop neovim-qt curl
sudo apt -y install grub-customizer
sudo apt -y install libreoffice evince gnome-calculator
sudo apt -y install software-properties-common
sudo apt -y install arandr rofi scrot x11vnc feh jq compton numlockx gsimplecal
sudo apt -y install pulseaudio pulseaudio-module-bluetooth pavucontrol bluez-firmware blueman
sudo apt -y install flatpak xdg-desktop-portal-gtk xdg-desktop-portal gnome-software gnome-software-plugin-flatpak
sudo apt -y install py3status acpi xclip imagemagick xbacklight
sudo apt -y install tcllib
sudo apt -y install libstdc++-9-doc
sudo apt -y install default-jre
sudo apt -y install default-jdk
sudo apt -y install nodejs
sudo apt -y install npm
sudo apt -y install snapd
sudo apt -y install cmake
sudo apt -y install silversearcher-ag
sudo apt -y install python3-pip
sudo pip3 install setuptools
sudo pip3 install pynvim
sudo pip3 install neovim-remote

print_banner "fonts"
sudo apt -y install fonts-inconsolata
sudo apt -y install ttf-ancient-fonts
sudo apt -y install fonts-noto-color-emoji libfreetype6 fontconfig libcairo-gobject2 libcairo2
upgrade nerd_fonts
#--------------------------------------------------------------

#--------------------------------------------------------------
# compiled from source / snap
#--------------------------------------------------------------
# dependencies:
#-- pinta
sudo apt -y install mono-xbuild automake autoconf gtk-sharp2 yelp-tools intltool
sudo apt -y install liblua5.1-dev luajit libluajit-5.1-common python-dev ruby-dev libperl-dev libncurses5-dev libatk1.0-dev libx11-dev libxpm-dev libxt-dev gnome-devel
#-- i3-gaps
sudo apt -y install gcc make dh-autoreconf libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev xcb libxcb1-dev libxcb-icccm4-dev libyajl-dev libev-dev libxcb-xkb-dev libxcb-cursor-dev libxkbcommon-dev libxcb-xinerama0-dev libxkbcommon-x11-dev libstartup-notification0-dev libxcb-randr0-dev libxcb-xrm0 libxcb-xrm-dev libxcb-shape0-dev
sudo apt -y install i3lock
sudo apt -y install wmctrl
#-- vim
sudo apt -y install libgtk-3-dev liblua5.1-dev luajit libluajit-5.1-common python3-dev python-dev ruby-dev libperl-dev libncurses5-dev libatk1.0-dev libx11-dev libxpm-dev libxt-dev gnome-devel
#-- universal ctags
sudo apt -y install \
  gcc make \
  pkg-config autoconf automake \
  python3-docutils \
  libseccomp-dev \
  libjansson-dev \
  libyaml-dev \
  libxml2-dev

mkdir -p ~/src

print_banner "alacritty"
upgrade alacritty
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/alacritty 60

print_banner "pinta"
cd ~/src
git clone https://github.com/PintaProject/Pinta
cd Pinta
./autogen.sh
make
sudo make install

print_banner "i3-gaps"
upgrade i3
cd ~/.config/i3/bin/i3lock
git submodule update --init --recursive
git pull --recurse-submodule
cat << EOF | sudo tee /etc/X11/xorg.conf
Section "Device"
        Identifier  "Intel Graphics"
        Driver      "intel"
        Option      "Backlight"  "intel_backlight"
EndSection
EOF

print_banner "nvim"
upgrade nvim

print_banner "universal ctags"
upgrade ctags

print_banner "LSP"
upgrade lsp

print_banner "bat"
upgrade bat
#--------------------------------------------------------------

print_banner "gtk theme"
sudo apt -y install lxappearance gtk-chtheme lightdm-gtk-greeter-settings
cat << EOF
lxappearance                 : choose a theme
gtk-chtheme                  : choose same theme
lightdm-gtk-greeter-settings : change login screen to your liking
EOF
