#!/bin/bash

# before running this script:
#   git clone http://github.com/antoinemadec/dotfiles
#   ./deploy

set -e
sudo -nv || { echo "Use sudo in this terminal before running the script"; exit 1; }

print_banner() {
  cat << EOF

#--------------------------------------------------------------
# $1
#--------------------------------------------------------------
EOF
}

print_banner "update system"
sudo pacman --noconfirm -Syyuu

print_banner "fonts"
sudo pacman --noconfirm -S noto-fonts-emoji
upgrade nerd_fonts

print_banner "python packages"
sudo pip3 install setuptools
sudo pip3 install pynvim
sudo pip3 install neovim-remote
sudo pip3 install rope
sudo pip3 install demucs # music source separation

print_banner "pacman packages"

# misc
sudo pacman --noconfirm -S alacritty libreoffice tig the_silver_searcher
sudo pacman --noconfirm -S baobab libnotify dunst audacity xdotool
sudo pacman --noconfirm -S rust
sudo pamac build --no-confirm tzupdate google-chrome deezer

# vim
sudo pacman --noconfirm -S nodejs npm yarn
sudo pacman --noconfirm -S xclip bat
sudo pacman --noconfirm -S luarocks ctags autopep8
sudo pamac  build --no-confirm neovim-nightly-bin
sudo pacman --noconfirm -S neovim-qt

# i3
sudo pacman --noconfirm -S gsimplecal gnome-calculator pinta
sudo pamac  build --no-confirm rofi-power-menu
sudo pacman --noconfirm -S py3status i3status feh rofi jq picom arandr scrot i3lock
sudo pacman --noconfirm -S i3-gaps
