[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7c6f64"
blue = "#80aa9e"
cyan = "#8bba7f"
green = "#b0b846"
magenta = "#d3869b"
red = "#f2594b"
white = "#e2cca9"
yellow = "#e9b143"

[colors.normal]
black = "#7c6f64"
blue = "#80aa9e"
cyan = "#8bba7f"
green = "#b0b846"
magenta = "#d3869b"
red = "#f2594b"
white = "#e2cca9"
yellow = "#e9b143"

[colors.primary]
background = "#32302f"
foreground = "#e2cca9"

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.bold]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"

[window.padding]
x = 1
y = 1
