#!/bin/bash

# Common to SVN and Git:
#   clean     '🌼'
#   modified  '🔥'
#   renamed   '⏩'
#   deleted   '❌'
#   untracked '❔'
#   ignored   '🚫'
#   other     '❗'

# Git specific
#   staged    '➕'

# Svn specific
#   added     '➕'

set -e

abs_path="$1"
buf_nb="$2"

if [[ "$abs_path" =~ 'fugitive:///' ]]; then
  vc_output='remote 👀'
  echo "$buf_nb $vc_output"
  exit 0
fi

[ -f "$abs_path" ] || exit 0
[ "$buf_nb" = "" ] && exit 0

abs_path="$(readlink -e "$abs_path")"
dir="$(dirname "$abs_path")"
filename="$(basename "$abs_path")"

# init
vc_output=""
git_fail=0
svn_fail=0


get_svn_status() {
  svn_status="$(svn st "$filename" 2>&1)" || svn_fail=1
  [[ "$svn_status" =~ "not a working" ]] && svn_fail=1
  if ((svn_fail == 0))
  then
    first_col="${svn_status:0:1}"
    other_col="${svn_status:1:6}"
    if [ "$other_col" != "" ] && [ "$other_col" != "      " ]
    then
      vc_output="svn ❗"
    else
      case "$first_col" in
        '')  vc_output="svn 🌼";;
        '?') vc_output="svn ❔";;
        'A') vc_output="svn ➕";;
        'D') vc_output="svn ❌";;
        'M') vc_output="svn 🔥";;
        'R') vc_output="svn ⏩";;
        'I') vc_output="svn 🚫";;
        *)   vc_output="svn ❗";;
      esac
    fi
  fi
}


get_git_status() {
  git_branch="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)" || git_fail=1
  if ((git_fail == 0))
  then
    git_status="$(git status --ignored=traditional --untracked-files=all --porcelain "$filename" |
      head -n1 2> /dev/null)" || git_fail=1
    if ((git_fail == 0))
    then
      us="${git_status:0:1}"
      them="${git_status:1:1}"
      if [ "$us" = '?' ] && [ "$them" = '?' ]
      then
        vc_output="$git_branch ❔"
      elif [ "$us" = ' ' ] && [ "$them" = 'M' ]
      then
        vc_output="$git_branch 🔥"
      elif [[ "$us" =~ [MAC] ]]
      then
        vc_output="$git_branch ➕"
      elif [ "$us" = 'R' ]
      then
        vc_output="$git_branch ⏩"
      elif [ "$them" = 'D' ]
      then
        vc_output="$git_branch ❌"
      elif [ "$us" = '!' ]
      then
        vc_output="$git_branch 🚫"
        # fix bug happing when:
        #   - filename='.file'
        #   - an git-ignored file starting with '.file' exists
        echo $filename > ~/toto.txt
        echo "${git_status/* /}" >> ~/toto.txt
        [ "$filename" = "${git_status/* /}" ] || vc_output="$git_branch 🌼"
      elif [ "$us" = '' ] && [ "$them" = '' ]
      then
        vc_output="$git_branch 🌼"
      else
        vc_output="$git_branch ❗"
      fi
    fi
  fi
}


if [ "$filename" != "" ]
then
  cd "$dir"
  get_svn_status
  ((svn_fail == 0)) || get_git_status
fi

echo "$buf_nb $vc_output"
